import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/providers/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

type Props = {
  params: { id: string }
  searchParams: { [key: string]: string | string[] | undefined }
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>,
) {
  return (
    <html lang="en">
      <head>
        <title>Hello world</title>
        <meta
          property="og:image"
          content={`https://cdn.maxion.gg/landverse/image/market/market_101.png`}
        />
        <meta property="og:title" content="Product Name" />
        <meta property="og:description" content="Buy this amazing product for only $99.99!" />
        <meta property="og:url" content="https://example.com/product-page-url" />
      </head>
      <body className={inter.className}>
        <ReactQueryProvider>
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
